### ISSUE TITLE
没有dirburp这个目录啊

### ISSUE THREAD

**Issue by h3litz** [0xa-saline/htcap_mysql#1]
```
$ python htcap.py                                                                                                                                                                [21:08:59]
Traceback (most recent call last):
  File "htcap.py", line 22, in <module>
    from core.crawl.crawler import Crawler
  File "/htcap_mysql/core/crawl/crawler.py", line 41, in <module>
    from core.dirburp.dirscan import Dirbuster
ImportError: No module named dirburp.dirscan
````

**Comment by 0xa-saline** [comment]
唔。dirburp.py其实这个是个采集和爆破目录以及文件的脚本.因为不完善.没有传上来.最近有些忙，还没有来得及完善。注释就好了
